kobis:
  api:
    scheme: http
    host: kobis.or.kr
    path:
      list: /kobisopenapi/webservice/rest/movie/searchMovieList.json
      detail: /kobisopenapi/webservice/rest/movie/searchMovieInfo.json