spring:
  application:
    name: silence
  datasource:
    url: jdbc:postgresql://localhost:5435/silence-movie
    username: silence_user
    password: silence_pwd
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true